### ISSUE TITLE
cloning error when using Github Desktop Option

### ISSUE THREAD

**Issue by jbisgrove** [PacktPublishing/Mastering-Transformers#1]
Windows 10 ::
![image](https://user-images.githubusercontent.com/2701527/165778386-bc17fec1-2a34-4e40-a6ad-84e39d7bab9c.png)

i have tried restarting the program and cloning. deleted folders and files. nothing clears the error.

i've been using the cloning option for other PacktPub Codesets without problems

**Comment by shubham763** [comment]
Hi @jbisgrove 

Thank you for informing us regarding the cloning issue, you can use an alternative and directly download the code files.

1) Click on the green color "Code" button :

![image](https://user-images.githubusercontent.com/60926838/167407170-7876ccea-d134-4cbc-8dd0-7e9e2b0c0051.png)

2) Click on "Download Zip":

![image](https://user-images.githubusercontent.com/60926838/167407328-2cc4f5e1-9fd4-45a9-979e-a25c80faaebb.png)

Please follow the above steps and you'll get the code files, and reopen the issue if the problem still persists.

Thanks and regards,
Shubham

**Comment by Jingyanya** [comment]
Hello @jbisgrove, @shubham763, I think this is because the folder 'CH10/CH10d_Load_testing_using_Locust ' has a 'space' at the very end. Can you fix this? I tried to clone then checkout branch 100ffbc and I received this error:
![image](https://github.com/PacktPublishing/Mastering-Transformers/assets/45839443/225986af-68ff-47ef-b654-6606d4241b92)

**Comment by Jingyanya** [comment]
Hello @jbisgrove, @shubham763, I think this is because the folder 'CH10/CH10d_Load_testing_using_Locust ' has a 'space' at the very end. Can you fix this? I tried to clone then checkout branch https://github.com/PacktPublishing/Mastering-Transformers/commit/100ffbc0da24911e4fd1fd7748f5df307658f049 and I received this error:
![image](https://github.com/PacktPublishing/Mastering-Transformers/assets/45839443/8e79ab32-22fb-46c3-ac90-721a5df2d32b)
